In [1]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in d:\anaconda3\envs\data1202\lib\site-packages (8.0.26)Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: protobuf>=3.0.0 in d:\anaconda3\envs\data1202\lib\site-packages (from mysql-connector-python) (3.18.1)

In [2]:
import mysql.connector as sql
import pandas as pd
import numpy as np

In [3]:
credential=pd.read_csv('D:/Assignment/1202 SQL/Assignment 3/mysql.txt', sep=',')
conn=sql.connect(host='localhost',user=credential.iat[0,0],password=credential.iat[0,1], db='video_game')
conn

In [4]:
df=pd.read_sql_query("SELECT * FROM vgsales", conn)
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,259,Asteroids,2600,1980,Shooter,Atari,4.00,0.26,0.00,0.05,4.31
1,545,Missile Command,2600,1980,Shooter,Atari,2.56,0.17,0.00,0.03,2.76
2,1768,Kaboom!,2600,1980,Misc,Activision,1.07,0.07,0.00,0.01,1.15
3,1971,Defender,2600,1980,Misc,Atari,0.99,0.05,0.00,0.01,1.05
4,2671,Boxing,2600,1980,Fighting,Activision,0.72,0.04,0.00,0.01,0.77
...,...,...,...,...,...,...,...,...,...,...,...
16322,16592,Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...,PSV,2016,Action,dramatic create,0.00,0.00,0.01,0.00,0.01
16323,14393,Phantasy Star Online 2 Episode 4: Deluxe Package,PS4,2017,Role-Playing,Sega,0.00,0.00,0.03,0.00,0.03
16324,16244,Phantasy Star Online 2 Episode 4: Deluxe Package,PSV,2017,Role-Playing,Sega,0.00,0.00,0.01,0.00,0.01
16325,16441,Brothers Conflict: Precious Baby,PSV,2017,Action,Idea Factory,0.00,0.00,0.01,0.00,0.01
16326,5959,Imagine: Makeup Artist,DS,2020,Simulation,Ubisoft,0.27,0.00,0.00,0.02,0.29

In [5]:
query1 = pd.read_sql('''SELECT 
    CASE
        WHEN year <= 2005 THEN 'pre-2005'
        ELSE 'post-2005'
    END Sales_Year,
    AVG(Global_Sales) AS Average_Global_Sales
FROM
    vgsales
GROUP BY Sales_year ORDER BY Average_Global_Sales DESC''', conn)

In [6]:
print(query1)

  Sales_Year  Average_Global_Sales
0   pre-2005              0.625084
1  post-2005              0.489448

In [7]:
query2 = pd.read_sql('''SELECT *, CASE
                     WHEN YEAR <=2005 THEN 'pre-2005'
                     ELSE 'post-2005'
                     END Sales_Period
                     FROM vgsales''', conn)
query2

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Sales_Period
0,259,Asteroids,2600,1980,Shooter,Atari,4.00,0.26,0.00,0.05,4.31,pre-2005
1,545,Missile Command,2600,1980,Shooter,Atari,2.56,0.17,0.00,0.03,2.76,pre-2005
2,1768,Kaboom!,2600,1980,Misc,Activision,1.07,0.07,0.00,0.01,1.15,pre-2005
3,1971,Defender,2600,1980,Misc,Atari,0.99,0.05,0.00,0.01,1.05,pre-2005
4,2671,Boxing,2600,1980,Fighting,Activision,0.72,0.04,0.00,0.01,0.77,pre-2005
...,...,...,...,...,...,...,...,...,...,...,...,...
16322,16592,Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...,PSV,2016,Action,dramatic create,0.00,0.00,0.01,0.00,0.01,post-2005
16323,14393,Phantasy Star Online 2 Episode 4: Deluxe Package,PS4,2017,Role-Playing,Sega,0.00,0.00,0.03,0.00,0.03,post-2005
16324,16244,Phantasy Star Online 2 Episode 4: Deluxe Package,PSV,2017,Role-Playing,Sega,0.00,0.00,0.01,0.00,0.01,post-2005
16325,16441,Brothers Conflict: Precious Baby,PSV,2017,Action,Idea Factory,0.00,0.00,0.01,0.00,0.01,post-2005
16326,5959,Imagine: Makeup Artist,DS,2020,Simulation,Ubisoft,0.27,0.00,0.00,0.02,0.29,post-2005

In [9]:
new_df = df
new_df.rename(columns={'Year':'Sales_Year'},inplace=True)
new_df["Sales_Period"] = np.where((new_df["Sales_Year"] <= 2005), "pre-2005", "post-2005")
new_df

,Rank,Name,Platform,Sales_Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Sales_Period
0,259,Asteroids,2600,1980,Shooter,Atari,4.00,0.26,0.00,0.05,4.31,pre-2005
1,545,Missile Command,2600,1980,Shooter,Atari,2.56,0.17,0.00,0.03,2.76,pre-2005
2,1768,Kaboom!,2600,1980,Misc,Activision,1.07,0.07,0.00,0.01,1.15,pre-2005
3,1971,Defender,2600,1980,Misc,Atari,0.99,0.05,0.00,0.01,1.05,pre-2005
4,2671,Boxing,2600,1980,Fighting,Activision,0.72,0.04,0.00,0.01,0.77,pre-2005
...,...,...,...,...,...,...,...,...,...,...,...,...
16322,16592,Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...,PSV,2016,Action,dramatic create,0.00,0.00,0.01,0.00,0.01,post-2005
16323,14393,Phantasy Star Online 2 Episode 4: Deluxe Package,PS4,2017,Role-Playing,Sega,0.00,0.00,0.03,0.00,0.03,post-2005
16324,16244,Phantasy Star Online 2 Episode 4: Deluxe Package,PSV,2017,Role-Playing,Sega,0.00,0.00,0.01,0.00,0.01,post-2005
16325,16441,Brothers Conflict: Precious Baby,PSV,2017,Action,Idea Factory,0.00,0.00,0.01,0.00,0.01,post-2005
16326,5959,Imagine: Makeup Artist,DS,2020,Simulation,Ubisoft,0.27,0.00,0.00,0.02,0.29,post-2005

In [10]:
new_df.groupby('Sales_Period', sort= "True")[['Global_Sales']].mean()

              Global_Sales
Sales_Period
post-2005         0.489448
pre-2005          0.625084